
version: 2
updates:
  # Update Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  # Update GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "monthly"
