# Simulation Domain (meters)
xlims: [0.0, 100e-6]
zlims: [0.0, 75e-6]

# Optical properties
wavelength: 6.35e-7
n_medium: 1.0 # Surrounding medium refractive index 1.0 (free space)

# --- Probe configuration ---
probe_dimensions_px
probe_diameter: 0.8e-6  # meters
probe_focus: -5e-6 # focal length [m]


# Scan configuration
detector_px: 40 # pixels
scan_points: 124 # number of scan points in one direction
step_size_px: 3 # step size in pixels
probe_angles: [-0.1, 0.0, 0.1]

# Boundary and Probe Form
bc_type: "impedance"
probe_type: "airy_disk"

# Object list
gaussian_blur_px: 3
sample_space_objects:
  - { type: "circle", centre: [0.3, 0.3],  side_length: 0.05, depth: 0.05 }
  - { type: "circle", centre: [0.5, 0.65], side_length: 0.05, depth: 0.05 }
  - { type: "circle", centre: [0.7, 0.65], side_length: 0.05, depth: 0.05 }
  - { type: "circle", centre: [0.4, 0.5],  side_length: 0.05, depth: 0.05 }
  - { type: "circle", centre: [0.6, 0.3],  side_length: 0.05, depth: 0.05 }
  - { type: "circle", centre: [0.3, 0.7],  side_length: 0.05, depth: 0.05 }

solver:
  poisson_noise: True
  max_iters: 10
  solve_probe: False
  rotate90: True
  known_phase: True
