# Simulation Domain (meters)
xlims: [0.0, 150e-6]
#ylims: (0.0, 100e-6)
zlims: [0.0, 40e-6]

# --- Probe configuration ---
probe_type: "airy_disk"
probe_diameter: 10e-6  # meters
probe_focus: -5e-6 # focal length [m]
wave_length: 6.35e-7 # meters
probe_tilts: [0.0] # radians


# --- Scan Configuration ---
step_size_px: 20 # pixels
scan_points: 60 # number of scan points in one direction
pad_factor: 2.0 # padding factor
solve_reduced_domain: True

# --- Z discretization ---
# > Overridden if rotate90 is True since nz=nx in that case
points_per_wavelength: 8
# nz: 50 # Overrides points_per_wavelength if specified

# --- Material configuration ---
n_medium: 1.0 # Surrounding medium refractive index 1.0 (free space)


# --- Simulated Objects ---
gaussian_blur: 3
random_circles: True
delta: 0.01
beta: 0.001



# Solver configuration
solver:
  solver_type: "iterativePWE"
  bc_type: "impedance"
  poisson_noise: False
  rotate90: False
