# Simulation Domain (meters)
xlims: [0.0, 150e-6]
#ylims: (0.0, 100e-6)
zlims: [0.0, 40e-6]

# --- Probe configuration ---
probe_type: "airy_disk"
probe_diameter: 10e-6  # meters
probe_focus: -5e-6 # focal length [m]
wave_length: 6.35e-7 # meters
probe_tilts: [0.0] # radians


# --- Scan Configuration ---
step_size_px: 10 # pixels
scan_points: 50 # number of scan points in one direction
pad_factor: 2.0 # padding factor
solve_reduced_domain: True

# --- Z discretization ---
# > Overridden if rotate90 is True since nz=nx in that case
points_per_wavelength: 8
# nz: 50 # Overrides points_per_wavelength if specified

# --- Material configuration ---
n_medium: 1.0 # Surrounding medium refractive index 1.0 (free space)

# Reconstruction Solver configuration
recon_solver:
  solver_type: "PWE"
  bc_type: "impedance"
  phase_retrieval: False
  rotate90: False
  max_iters: 10
  data_file_path: "results/sim/2025-12-08_18-57-15/simulated_data.npz"