# Boundary Conditions
# impedance / dirichlet / neumann
bc_type: "impedance"
# constant / gaussian / sinusoidal / complex_exp 
# / dirichlet_test / neumann_test / airy_disk 
# / disk / blurred_disk
probe_type: "airy_disk"

# Probe angles
probe_angles_list: [0.0]

wavelength: 6.35e-7

# Background Refractive Index
nb: 1.0
# Refractive Index Perturbation
delta: 0.01                       # Re(n) perturbation
beta: 0.001                       # Im(n) perturbation

# Continuous domain (meters)
xlims: [0.0, 0.00015]           # [0, 150 µm]
zlims: [0.0, 0.00015]           # [0, 150 µm]

# z steps per wavelength
z_step_per_wavelength: 2

# Discrete domain (pixels)
probe_dimensions_px: [40]       
probe_diameter_fraction: 0.8 
scan_points: 124
step_size_px: 3
probe_focus: -1.0e-5

# Add Shapes to 
# side_length_fraction multiplies xlims_m[1]; depth_fraction multiplies zlims_m[1].
gaussian_blur_px: 3
sample_space_objects:
  - type: "circle"
    side_length_fraction: 0.05
    centre_fraction: [0.3, 0.3]
    depth_fraction: 0.05
  - type: "circle"
    side_length_fraction: 0.05
    centre_fraction: [0.5, 0.65]
    depth_fraction: 0.05
  - type: "circle"
    side_length_fraction: 0.05
    centre_fraction: [0.7, 0.65]  
    depth_fraction: 0.05
  - type: "circle"
    side_length_fraction: 0.05
    centre_fraction: [0.4, 0.5] 
    depth_fraction: 0.05
  - type: "circle"
    side_length_fraction: 0.05
    centre_fraction: [0.6, 0.3]  
    depth_fraction: 0.05
  - type: "circle"
    side_length_fraction: 0.05
    centre_fraction: [0.3, 0.7]  
    depth_fraction: 0.05

# Solver options
solver:
  full_system_solver: false
  max_iters: 50
  plot_forward: false
  plot_reverse: false
  plot_object: true
  solve_probe: false
  sparsity_lambda: 0.0 # 2.0e-5
  low_pass_filter: 0.0
  rotate90: False
